apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: "{{ .Values.bridge.topic }}-bridge-kafka"
  labels:
    strimzi.io/cluster: {{ .Release.Name }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name:  "{{ .Values.bridge.topic }}-uplinks"
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
      - resource:
          type: topic
          name:  "{{ .Values.bridge.topic }}-errors"
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
---