apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: "{{ .Values.bridge.topic }}-bridge-kafka"
  labels:
    strimzi.io/cluster: {{ .Release.Name }}
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "{{ .Values.bridge.topic }}-uplinks"
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: "{{ .Values.bridge.topic }}-errors"
          patternType: literal
        operation: Write
      - resource:
          type: topic
          name: __consumer_offsets
          patternType: literal
        operation: Write
      - resource:
          type: group
          name: truvami-bridge
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: truvami-bridge
          patternType: literal
        operation: Read
---