apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: "{{ .Values.bridge.topic }}-bridge-kafka"
  labels:
    strimzi.io/cluster: {{ .Release.Name }}
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: '*'
        operations:
          - Read
          - Describe
        resource:
          name: truvami-uplinks
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Create
          - Describe
          - Write
        resource:
          name: truvami-errors
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Write
        resource:
          name: __consumer_offsets
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Describe
          - Write
        resource:
          name: {{ .Values.bridge.kafka.alerts.topics.uplinks }}
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Describe
          - Write
        resource:
          name: {{ .Values.bridge.kafka.alerts.topics.positions }}
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Describe
          - Write
        resource:
          name: "battery-statuses"
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Describe
          - Write
        resource:
          name: {{ .Values.bridge.kafka.alerts.topics.rotations }}
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Read
          - Describe
          - Write
        resource:
          name: {{ .Values.bridge.kafka.alerts.topics.events }}
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Describe
          - Read
          - Write
        resource:
          name: {{ .Release.Name }}
          patternType: literal
          type: group
{{- with .Values.kafka.additionalAcls }}
{{ toYaml . | nindent 6 }}
{{- end }}
    type: simple
