apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-bridge
spec:
  groups:
    - name: truvami-bridge
      rules:
        - alert: TruvamiBridgeConnectionTimeout
          annotations:
            description: >-
              The service `truvami-bridge` logged "Connection setup timed out"
              within the last 5 minutes. Please check the bridge connectivity and upstream dependencies.
            summary: >-
              Connection setup timeout detected in truvami-bridge
          expr: >-
            sum by (namespace, service_name) (
              count_over_time(
                {service_name="truvami-bridge"} |= "Connection setup timed out" [5m]
              )
            ) > 0
          for: 2m
          labels:
            altravis_prod: "true"
            altravis_test: "true"
            service: truvami-bridge
            severity: warning
            code: SBCC
            customer: truvami
            node: sbcc-cluster-7401-truvami-bridge
