apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "truvami-monitoring.fullname" . }}-prometheus"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "truvami-monitoring.fullname" . }}-prometheus"
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs: ["get", "list", "watch"]
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "truvami-monitoring.fullname" . }}-prometheus"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "truvami-monitoring.fullname" . }}-prometheus"
subjects:
- kind: ServiceAccount
  name: "{{ include "truvami-monitoring.fullname" . }}-prometheus"
  namespace: {{ .Release.Namespace }}
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: "{{ include "truvami-monitoring.fullname" . }}-prometheus"
spec:
  serviceAccountName: "{{ include "truvami-monitoring.fullname" . }}-prometheus"
  replicas: 2
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  logFormat: "json"
  retention: 10d
  ruleNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name : {{ .Release.Namespace }}
  ruleSelector: {}
  scrapeConfigNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name : {{ .Release.Namespace }}
  scrapeConfigSelector: {}
  serviceMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name : {{ .Release.Namespace }}
  serviceMonitorSelector: {}
  alerting:
    alertmanagers:
    - namespace: {{ .Release.Namespace }}
      name: "{{ include "truvami-monitoring.fullname" . }}-alertmanager"
      port: web
---
apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: "{{ include "truvami-monitoring.fullname" . }}-alertmanager"
spec:
  replicas: 2
