apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: siren-alert-processing
spec:
  groups:
    - name: siren-alert-processing
      rules:
        - alert: SirenUplinkProcessingFailures
          annotations:
            description: >-
              Siren uplink processing failure rate is {{ "{{" }} $value }} failures/sec for topic {{ "{{" }} $labels.topic }}.
            summary: >-
              High Siren uplink processing failure rate
          expr: >-
            rate(truvami_alerts_uplinks_processed_error_count[5m]) > 0.1
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: siren-{{ "{{" }} $labels.topic }}
            service: truvami-siren
            component: alert-processing
        - alert: SirenPositionProcessingFailures
          annotations:
            description: >-
              Siren position processing failure rate is {{ "{{" }} $value }} failures/sec for topic {{ "{{" }} $labels.topic }}.
            summary: >-
              High Siren position processing failure rate
          expr: >-
            rate(truvami_alerts_positions_processed_error_count[5m]) > 0.1
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: siren-{{ "{{" }} $labels.topic }}
            service: truvami-siren
            component: alert-processing
        - alert: SirenBatteryStatusProcessingFailures
          annotations:
            description: >-
              Siren battery status processing failure rate is {{ "{{" }} $value }} failures/sec for topic {{ "{{" }} $labels.topic }}.
            summary: >-
              High Siren battery status processing failure rate
          expr: >-
            rate(truvami_alerts_battery_statuses_processed_error_count[5m]) > 0.1
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: siren-{{ "{{" }} $labels.topic }}
            service: truvami-siren
            component: alert-processing
        - alert: SirenRotationStatusProcessingFailures
          annotations:
            description: >-
              Siren rotation status processing failure rate is {{ "{{" }} $value }} failures/sec for topic {{ "{{" }} $labels.topic }}.
            summary: >-
              High Siren rotation status processing failure rate
          expr: >-
            rate(truvami_alerts_rotations_statuses_processed_error_count[5m]) > 0.1
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: siren-{{ "{{" }} $labels.topic }}
            service: truvami-siren
            component: alert-processing
        - alert: SirenEventProcessingFailures
          annotations:
            description: >-
              Siren event processing failure rate is {{ "{{" }} $value }} failures/sec for topic {{ "{{" }} $labels.topic }}.
            summary: >-
              High Siren event processing failure rate
          expr: >-
            rate(truvami_alerts_events_processed_error_count[5m]) > 0.1
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: siren-{{ "{{" }} $labels.topic }}
            service: truvami-siren
            component: alert-processing
        - alert: SirenAlertProcessingRateHigh
          annotations:
            description: >-
              Siren alert processing rate is unusually high at {{ "{{" }} $value }} alerts/sec.
            summary: >-
              Unusually high Siren alert processing rate
          expr: >-
            (
              rate(truvami_alerts_uplinks_processed_count[5m]) +
              rate(truvami_alerts_positions_processed_count[5m]) +
              rate(truvami_alerts_battery_statuses_processed_count[5m]) +
              rate(truvami_alerts_rotations_statuses_processed_count[5m]) +
              rate(truvami_alerts_events_processed_count[5m])
            ) > 50
          for: 5m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: intermediate
            node: truvami-siren
            service: truvami-siren
            component: alert-processing
        - alert: SirenAlertProcessingRateLow
          annotations:
            description: >-
              Siren alert processing rate is unusually low at {{ "{{" }} $value }} alerts/sec - possible system issue.
            summary: >-
              Unusually low Siren alert processing rate
          expr: >-
            (
              rate(truvami_alerts_uplinks_processed_count[5m]) +
              rate(truvami_alerts_positions_processed_count[5m]) +
              rate(truvami_alerts_battery_statuses_processed_count[5m]) +
              rate(truvami_alerts_rotations_statuses_processed_count[5m]) +
              rate(truvami_alerts_events_processed_count[5m])
            ) < 0.01
          for: 10m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
            node: truvami-siren
            service: truvami-siren
            component: alert-processing