apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-gateway-network
spec:
  groups:
    - name: truvami-gateway-network
      rules:
        - alert: TruvamiBadGatewayRSSI
          annotations:
            description: >
              Gateway {{ "{{" }} $labels.gatewayId }} has average RSSI of {{ "{{" }} $value }} dBm over the last 24 hours, which is below the -120 dBm threshold.
            summary: >
              Bad Truvami gateway RSSI detected (24h average)
          expr: >
            avg by (gatewayId) (avg_over_time(truvami_gateway_uplink_rssi[1d])) < -120
          for: 30m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: minor
            node: truvami-gateway-{{ "{{" }} $labels.gatewayId }}
        - alert: TruvamiBadGatewaySNR
          annotations:
            description: >
              Gateway {{ "{{" }} $labels.gatewayId }} has average SNR of {{ "{{" }} $value }} dB over the last 24 hours, which is below the -10 dB threshold.
            summary: >
              Bad Truvami gateway SNR detected (24h average)
          expr: >
            avg by (gatewayId) (avg_over_time(truvami_gateway_uplink_snr[1d])) < -10
          for: 30m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: minor
            node: truvami-gateway-{{ "{{" }} $labels.gatewayId }}