apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-kafka-consumer
spec:
  groups:
    - name: truvami-kafka-consumer
      rules:
        - alert: TruvamiKafkaConsumerLag
          annotations:
            description: >-
              No messages consumed for more than 15 minutes. Last message was {{ "{{" }} $value | humanizeDuration }} ago.
            summary: >-
              Truvami Kafka consumer lag detected
          expr: >-
            time() - truvami_kafka_consumer_last_message_timestamp_seconds > 900
          for: 1m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: warning
        - alert: KafkaConsumerBlocked
          annotations:
            description: >-
              Kafka consumer appears blocked or in infinite loop - no messages processed for more than 30 minutes. Immediate attention required.
              Check the consumer health, Kafka connectivity, and system resources.
            summary: >-
              Kafka consumer appears blocked or in infinite loop
          expr: >-
            time() - truvami_kafka_consumer_last_message_timestamp_seconds > 1800
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: critical