apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-wifi-location
spec:
  groups:
    - name: truvami-wifi-location
      rules:
        - alert: TruvamiWiFiSolverHighErrorRate
          annotations:
            description: >-
              WiFi solver error rate is {{ "{{" }} $value | humanizePercentage }} over the last 5 minutes.
            summary: >-
              High Truvami WiFi solver error rate
          expr: >-
            rate(truvami_wifi_solver_error_count[5m]) / 
            (rate(truvami_wifi_solver_requests_count[5m]) + rate(truvami_wifi_solver_error_count[5m])) > 0.1
          for: 5m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: major
        - alert: TruvamiWiFiSolverDown
          annotations:
            description: >-
              No WiFi solver activity detected for 10 minutes.
            summary: >-
              Truvami WiFi solver appears to be down
          expr: >-
            rate(truvami_wifi_solver_requests_count[10m]) == 0 and 
            rate(truvami_wifi_solver_success_count[10m]) == 0 and 
            rate(truvami_wifi_solver_error_count[10m]) == 0
          for: 10m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: critical
        - alert: TruvamiHighWiFiZeroPositions
          annotations:
            description: >-
              WiFi solver returning zero positions at {{ "{{" }} $value }} occurrences/sec with {{ "{{" }} $labels.accessPointCount }} access points.
            summary: >-
              High rate of Truvami WiFi zero positions
          expr: >-
            rate(truvami_wifi_zero_position_count[5m]) > 0.5
          for: 5m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: warning