apiVersion: monitoring.core        - alert: TruvamiPositionEstimationErrorMinor
          annotations:
            description: >
              Position estimation success rate is {{ "{{" }} $value | humanizePercentage }} within the last 2h. Consider checking solver configuration.
            summary: >
              Truvami position estimation success rate below optimal
          expr: >
            (sum by(namespace) (increase(truvami_aws_position_estimates_success_total{namespace="truvami-dev"}[2h])) / sum by(namespace) (increase(truvami_aws_position_estimates_total{namespace="truvami-dev"}[2h]))) * 100 < 85
          for: 10m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: minor
        - alert: TruvamiPositionEstimationErrorWarning
          annotations:
            description: >
              Position estimation success rate is {{ "{{" }} $value | humanizePercentage }} within the last 2h. Please check the solver configuration.
            summary: >
              Truvami position estimation success rate degraded
          expr: >
            (sum by(namespace) (increase(truvami_aws_position_estimates_success_total{namespace="truvami-dev"}[2h])) / sum by(namespace) (increase(truvami_aws_position_estimates_total{namespace="truvami-dev"}[2h]))) * 100 < 75
          for: 5m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: warning
        - alert: TruvamiPositionEstimationErrorCritical
          annotations:
            description: >
              Position estimation success rate is {{ "{{" }} $value | humanizePercentage }} within the last 2h. Immediate attention required - check solver configuration and AWS positioning service.
            summary: >
              Critical Truvami position estimation failure rate
          expr: >
            (sum by(namespace) (increase(truvami_aws_position_estimates_success_total{namespace="truvami-dev"}[2h])) / sum by(namespace) (increase(truvami_aws_position_estimates_total{namespace="truvami-dev"}[2h]))) * 100 < 60
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: critical PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-decoder
spec:
  groups:
    - name: truvami-decoder
      rules:
        - alert: TruvamiDecoderFailedToDecodePayload
          annotations:
            description: >-
              Decoder failed to decode payload for device {{ "{{" }} $labels.devEui }} within the last 2h. Please check the decoder configuration and the payload format.
            summary: >-
              Decoder failed to decode payload for device {{ "{{" }} $labels.devEui }}
          expr: >-
            sum by(devEui) (increase(truvami_failed_to_decode_payload_count[2h])) > 0
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: warning
            node: truvami-{{ "{{" }} $labels.devEui }}
        - alert: TruvamiPositionEstimationError
          annotations:
            description: >-
              Position estimation failed to solve {{ "{{" }} $value | humanizePercentage }} positions within the last 2h. Please check the solver configuration.
            summary: >-
              Position estimation failed to solve {{ "{{" }} $value | humanizePercentage }} positions
          expr: >-
            (sum by(namespace) (increase(truvami_aws_position_estimates_success_total{namespace="truvami-dev"}[2h])) / sum by(namespace) (increase(truvami_aws_position_estimates_total{namespace="truvami-dev"}[2h]))) * 100 < 70
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: critical
        - alert: TruvamiWiFiSolverError
          annotations:
            description: >-
              The Wi-Fi solver returned an error, please check the logs for more details.
            summary: >-
              Wi-Fi solver error
          expr: >-
            rate(truvami_wifi_solver_error_count[1h]) > 0
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: critical