apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-device-battery-alerts
spec:
  groups:
    - name: truvami-device-battery-alerts
      rules:
        - alert: TruvamiDeviceBatteryCriticallyLow
          annotations:
            description: >-
              **What's happening:** Device {{ "{{" }} $labels.devEui }} (customer: {{ "{{" }} $labels.customer }}) has critically low battery at {{ "{{" }} $value }}V (<2.5V).
              
              **Why this occurred:** The device battery has dropped below the critical threshold of 2.5V.
              At this level, the device may:
              - Stop transmitting data completely
              - Experience erratic behavior or data corruption
              - Enter emergency power-saving mode
              - Risk permanent damage to the battery
              
              **What to do:**
              1. **IMMEDIATE**: Schedule battery replacement for device {{ "{{" }} $labels.devEui }}
              2. Contact customer {{ "{{" }} $labels.customer }} for maintenance scheduling
              3. Monitor device for complete communication loss
              4. Check if device has any remaining scheduled transmissions
              5. Document battery replacement in device maintenance log
            summary: >-
              Device {{ "{{" }} $labels.devEui }} battery critically low ({{ "{{" }} $value }}V <2.5V)
          expr: >-
            truvami_device_battery_status < 2.5
          for: 1m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: critical
            node: "{{ "{{" }} $labels.devEui }}"
            service: truvami-device
            component: battery
            customer: "{{ "{{" }} $labels.customer }}"
            devEui: "{{ "{{" }} $labels.devEui }}"
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

        - alert: TruvamiDeviceBatteryVeryLow
          annotations:
            description: >-
              **What's happening:** Device {{ "{{" }} $labels.devEui }} (customer: {{ "{{" }} $labels.customer }}) has very low battery at {{ "{{" }} $value }}V (<2.8V).
              
              **Why this occurred:** Battery voltage has dropped significantly and the device is approaching critical levels.
              This indicates the battery should be replaced soon to prevent service interruption.
              
              **What to do:**
              1. Schedule battery replacement within 1-2 weeks
              2. Notify customer {{ "{{" }} $labels.customer }} of upcoming maintenance need
              3. Monitor battery level daily for further decline
              4. Prepare replacement battery and maintenance schedule
            summary: >-
              Device {{ "{{" }} $labels.devEui }} battery very low ({{ "{{" }} $value }}V <2.8V)
          expr: >-
            truvami_device_battery_status < 2.8 and truvami_device_battery_status >= 2.5
          for: 5m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: "{{ "{{" }} $labels.devEui }}"
            service: truvami-device
            component: battery
            customer: "{{ "{{" }} $labels.customer }}"
            devEui: "{{ "{{" }} $labels.devEui }}"
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

        - alert: TruvamiDeviceBatteryDegraded
          annotations:
            description: >-
              **What's happening:** Device {{ "{{" }} $labels.devEui }} (customer: {{ "{{" }} $labels.customer }}) has degraded battery at {{ "{{" }} $value }}V (<3.2V).
              
              **Why this occurred:** Battery performance is declining and should be monitored for replacement planning.
              
              **What to do:**
              1. Add device to battery replacement planning list
              2. Monitor battery trend over coming weeks
              3. Plan maintenance visit when convenient
            summary: >-
              Device {{ "{{" }} $labels.devEui }} battery degraded ({{ "{{" }} $value }}V <3.2V)
          expr: >-
            truvami_device_battery_status < 3.2 and truvami_device_battery_status >= 2.8
          for: 15m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: minor
            node: "{{ "{{" }} $labels.devEui }}"
            service: truvami-device
            component: battery
            customer: "{{ "{{" }} $labels.customer }}"
            devEui: "{{ "{{" }} $labels.devEui }}"
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}