{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "truvami-monitoring.fullname" . }}-decoder-errors
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "truvami-monitoring.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: truvami.decoder.errors
    interval: {{ .Values.prometheusRule.interval | default "30s" }}
    rules:
    - alert: TruvamiDecodingErrors
      expr: rate(truvami_payloadparser_error_total[5m]) > 0.1
      for: 2m
      labels:
        severity: major
        service: truvami-bridge
        component: decoder
        node: "{{ "{{" }} $labels.devEui }}"
        {{- with .Values.alertLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "High payload decoding error rates"
        description: |
          High decoder error rates ({{ "{{" }} $value }}/sec) - payload decoding failures detected for device {{ "{{" }} $labels.devEui }}.
          
          This indicates issues with:
          - Device payload format changes
          - Decoder configuration problems
          - Corrupted or malformed payloads
          
    - alert: TruvamiDecodingErrorsCritical
      expr: rate(truvami_payloadparser_error_total[5m]) > 1
      for: 1m
      labels:
        severity: critical
        service: truvami-bridge
        component: decoder
        node: "{{ "{{" }} $labels.devEui }}"
        {{- with .Values.alertLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "Critical payload decoding error rates"
        description: |
          Critical decoder error rates ({{ "{{" }} $value }}/sec) - immediate attention required for payload decoding failures for device {{ "{{" }} $labels.devEui }}.
          
          This requires immediate investigation of:
          - Device firmware compatibility
          - Decoder service health
          - Network connectivity issues
          - Payload corruption at the source

{{- end }}