apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-service-health
spec:
  groups:
    - name: truvami-service-health
      rules:
        - alert: TruvamiBridgeDown
          annotations:
            description: >-
              **What's happening:** Truvami Bridge instance {{ "{{" }} $labels.instance }} is completely down and unresponsive for over 1 minute. CRITICAL SERVICE FAILURE.
              
              **Why this occurred:** The system monitors service availability using up{job="truvami-bridge"} == 0
              which indicates the service failed health checks. Truvami Bridge is critical infrastructure that processes all device data. Failure causes include:
              - Service crash or unexpected termination
              - System resource exhaustion (out of memory, CPU overload)
              - Database connectivity failure preventing startup
              - Configuration errors or missing dependencies
              - Network connectivity issues
              - Host system failure or maintenance
              
              **Business Impact:**
              - **COMPLETE SERVICE OUTAGE:** No device data processing
              - All device communications blocked
              - Real-time alerts and monitoring stopped
              - Customer data collection halted
              - API services may be affected
              
              **What to do IMMEDIATELY:**
              1. **ESCALATE TO ON-CALL IMMEDIATELY** - this is a P1 incident
              2. **Check service status** and restart if possible
              3. **Verify system resources** and host health
              4. **Check database connectivity** and dependencies
              5. **Review service logs** for crash details
              6. **Prepare customer communications** about service impact
              7. **Monitor for data loss** during outage period
            summary: >-
              Truvami Bridge is down - CRITICAL SERVICE OUTAGE
          expr: >-
            up{job="truvami-bridge"} == 0
          for: 1m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: critical
            node: truvami-bridge
        - alert: TruvamiBridgeHighErrorRate
          annotations:
            description: >-
              High error rate detected over the last 5 minutes.
            summary: >-
              High error rate in Truvami Bridge (>0.1 errors/sec over 5min, alert after 2min)
          expr: >-
            (
              rate(truvami_failed_to_decode_payload_count[5m]) +
              rate(truvami_failed_to_create_uplink_through_grpc_count[5m]) +
              rate(truvami_failed_to_fetch_device_metadata_count[5m])
            ) > 0.1
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: major
            node: truvami-bridge