apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-gateway-device-count
spec:
  groups:
    - name: truvami-gateway-device-monitoring
      rules:
        - alert: TruvamiGatewayDeviceCountLow
          annotations:
            description: >-
              Gateway {{ "{{" }} $labels.gatewayId }} active device count is low: {{ "{{" }} $value }} devices.
            summary: >-
              Gateway active device count low
          expr: >-
            truvami_gateway_active_device_count < 5
          for: 30m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: minor
            node: "{{ "{{" }} $labels.gatewayId }}"
            namespace: {{ .Release.Namespace }}
            component: gateway-monitoring