apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: siren-alert-dispatch
spec:
  groups:
    - name: siren-alert-dispatch
      rules:
        - alert: SirenAlertDispatchFailures
          annotations:
            description: >-
              Siren alert dispatch failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }} with schema {{ "{{" }} $labels.schema }}.
            summary: >-
              Critical Siren alert dispatch failure rate
          expr: >-
            rate(truvami_alerts_dispatch_errors_count[5m]) > 0.1
          for: 1m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: critical
            node: truvami-siren
            service: truvami-siren
            component: alert-dispatch
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

        - alert: SirenWebhookDispatchFailures
          annotations:
            description: >-
              Siren webhook dispatch failure rate is {{ "{{" }} $value }} failures/sec for webhook type {{ "{{" }} $labels.webhook_type }}.
            summary: >-
              High Siren webhook dispatch failure rate
          expr: >-
            rate(truvami_alerts_webhook_dispatch_error_count[5m]) > 0.05
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: truvami-siren
            service: truvami-siren
            component: alert-dispatch
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

        - alert: SirenDispatchWorkerPoolExhaustion
          annotations:
            description: >-
              Siren dispatch worker pool is exhausted - all {{ "{{" }} $value }} workers are busy.
            summary: >-
              Siren dispatch worker pool exhausted
          expr: >-
            truvami_alerts_dispatch_workers_busy == truvami_alerts_dispatch_workers_total
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: truvami-siren
            service: truvami-siren
            component: alert-dispatch
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
