apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: siren-device-alerts
spec:
  groups:
    - name: siren-device-alerts
      rules:
        - alert: SirenDeviceInactiveProcessingFailures
          annotations:
            description: >-
              Siren device inactive alert processing failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }}.
            summary: >-
              High Siren device inactive processing failure rate
          expr: >-
            rate(truvami_alerts_device_inactive_processing_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: siren
            severity: major
            node: siren-{{ "{{" }} $labels.devEui }}
        - alert: SirenDeviceActiveProcessingFailures
          annotations:
            description: >-
              Siren device active alert processing failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }}.
            summary: >-
              High Siren device active processing failure rate
          expr: >-
            rate(truvami_alerts_device_active_processing_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: siren
            severity: major
            node: siren-{{ "{{" }} $labels.devEui }}
        - alert: SirenBatteryLowAlertFailures
          annotations:
            description: >-
              Siren battery low alert processing failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }}.
            summary: >-
              High Siren battery low alert failure rate
          expr: >-
            rate(truvami_alerts_battery_low_processing_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: siren
            severity: major
            node: siren-{{ "{{" }} $labels.devEui }}
        - alert: SirenButtonPressAlertFailures
          annotations:
            description: >-
              Siren button press alert processing failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }}.
            summary: >-
              High Siren button press alert failure rate
          expr: >-
            rate(truvami_alerts_button_press_processing_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: siren
            severity: major
            node: siren-{{ "{{" }} $labels.devEui }}
        - alert: SirenConfigChangeAlertFailures
          annotations:
            description: >-
              Siren config change alert processing failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }}.
            summary: >-
              High Siren config change alert failure rate
          expr: >-
            rate(truvami_alerts_config_change_processing_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: siren
            severity: major
            node: siren-{{ "{{" }} $labels.devEui }}
        - alert: SirenFirmwareChangeAlertFailures
          annotations:
            description: >-
              Siren firmware change alert processing failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }}.
            summary: >-
              High Siren firmware change alert failure rate
          expr: >-
            rate(truvami_alerts_firmware_change_processing_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: siren
            severity: major
            node: siren-{{ "{{" }} $labels.devEui }}
        - alert: SirenDeviceResetAlertFailures
          annotations:
            description: >-
              Siren device reset alert processing failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }}.
            summary: >-
              High Siren device reset alert failure rate
          expr: >-
            rate(truvami_alerts_device_reset_processing_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: siren
            severity: major
            node: siren-{{ "{{" }} $labels.devEui }}
        - alert: SirenDutyCycleAlertFailures
          annotations:
            description: >-
              Siren duty cycle alert processing failure rate is {{ "{{" }} $value }} failures/sec for device {{ "{{" }} $labels.devEui }}.
            summary: >-
              High Siren duty cycle alert failure rate
          expr: >-
            rate(truvami_alerts_duty_cycle_processing_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: siren
            severity: major
            node: siren-{{ "{{" }} $labels.devEui }}