apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-gateway-network
spec:
  groups:
    - name: truvami-gateway-network
      rules:
        - alert: TruvamiLowGatewayRSSI
          annotations:
            description: >
              Gateway {{ "{{" }} $labels.gatewayId }} receiving weak signal ({{ "{{" }} $value }} dBm) from device {{ "{{" }} $labels.devEui }}.
            summary: >
              Low Truvami gateway RSSI detected
          expr: >
            truvami_gateway_uplink_rssi < -120
          for: 5m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: minor
            node: truvami-gateway-{{ "{{" }} $labels.gatewayId }}
        - alert: TruvamiLowGatewaySNR
          annotations:
            description: >
              Gateway {{ "{{" }} $labels.gatewayId }} has low SNR ({{ "{{" }} $value }} dB) for device {{ "{{" }} $labels.devEui }}.
            summary: >
              Low Truvami gateway SNR detected
          expr: >
            truvami_gateway_uplink_snr < -10
          for: 5m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: minor
            node: truvami-gateway-{{ "{{" }} $labels.gatewayId }}