apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-bridge
spec:
  groups:
    - name: truvami-bridge
      rules:
        - alert: TruvamiDeviceNoUplink24h
          annotations:
            description: >-
              Device {{ "{{" }} $labels.devEui }} has not sent any uplinks within the last 24 hours.
            summary: >-
              Device {{ "{{" }} $labels.devEui }} no uplinks in 24h (sum=0, alert after 5min).
          expr: >-
            sum by(devEui) (increase(truvami_device_uplink_count[24h])) == 0
          for: 5m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: intermediate
            node: truvami-device
            service: truvami-device
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - alert: TruvamiDeviceNoUplink72h
          annotations:
            description: >-
              Device {{ "{{" }} $labels.devEui }} has not sent any uplinks within the last 72 hours.
            summary: >-
              Device {{ "{{" }} $labels.devEui }} no uplinks in 72h (sum=0, alert after 5min).
          expr: >-
            sum by(devEui) (increase(truvami_device_uplink_count[72h])) == 0
          for: 5m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
            node: truvami-device
            service: truvami-device
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
