{{- if .Values.alerts.deviceBattery.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-device-battery-alerts
spec:
  groups:
    - name: truvami-device-battery-alerts
      rules:
        {{- if .Values.alerts.deviceBattery.criticallyLow.enabled }}
        - alert: TruvamiDeviceBatteryCriticallyLow
          annotations:
            description: >-
              **What's happening:** Device {{ "{{" }} $labels.devEui }} (customer: {{ "{{" }} $labels.customer }}) has critically low battery at {{ "{{" }} $value }}V (<2.5V).

              **Why this occurred:** The device battery has dropped below the critical threshold of 2.5V.
              At this level, the device may:
              - Stop transmitting data completely
              - Enter emergency power-saving mode

              **What to do:**
              1. **IMMEDIATE**: Schedule battery replacement / charging for device {{ "{{" }} $labels.devEui }}
              2. Contact customer {{ "{{" }} $labels.customer }} for maintenance scheduling
              3. Monitor device for complete communication loss
            summary: >-
              Device {{ "{{" }} $labels.devEui }} battery critically low <{{ .Values.alerts.deviceBattery.criticallyLow.threshold }}V
          expr: >-
            truvami_device_battery_status < {{ .Values.alerts.deviceBattery.criticallyLow.threshold }}
          for: {{ .Values.alerts.deviceBattery.criticallyLow.duration }}
          labels:
            namespace: {{ .Release.Namespace }}
            severity: {{ .Values.alerts.deviceBattery.criticallyLow.severity }}
            node: "{{ "{{" }} $labels.devEui }}"
            service: truvami-device
            component: battery
            customer: "{{ "{{" }} $labels.customer }}"
            devEui: "{{ "{{" }} $labels.devEui }}"
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- end }}

        {{- if .Values.alerts.deviceBattery.veryLow.enabled }}
        - alert: TruvamiDeviceBatteryVeryLow
          annotations:
            description: >-
              **What's happening:** Device {{ "{{" }} $labels.devEui }} (customer: {{ "{{" }} $labels.customer }}) has very low battery at {{ "{{" }} $value }}V (<{{ .Values.alerts.deviceBattery.veryLow.threshold }}V).

              **Why this occurred:** Battery voltage has dropped significantly and the device is approaching critical levels.
              This indicates the battery should be replaced soon to prevent service interruption.

              **What to do:**
              1. Schedule battery replacement / charging within next days
              2. Notify customer {{ "{{" }} $labels.customer }} of upcoming maintenance need
              3. Monitor battery level daily for further decline
            summary: >-
              Device {{ "{{" }} $labels.devEui }} battery very low <{{ .Values.alerts.deviceBattery.veryLow.threshold }}V
          expr: >-
            truvami_device_battery_status < {{ .Values.alerts.deviceBattery.veryLow.threshold }} and truvami_device_battery_status >= {{ .Values.alerts.deviceBattery.criticallyLow.threshold }}
          for: {{ .Values.alerts.deviceBattery.veryLow.duration }}
          labels:
            namespace: {{ .Release.Namespace }}
            severity: {{ .Values.alerts.deviceBattery.veryLow.severity }}
            node: "{{ "{{" }} $labels.devEui }}"
            service: truvami-device
            component: battery
            customer: "{{ "{{" }} $labels.customer }}"
            devEui: "{{ "{{" }} $labels.devEui }}"
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        {{- end }}
{{- end }}
