apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-gateway-network
spec:
  groups:
    - name: truvami-gateway-network
      rules:
        - alert: TruvamiPoorGatewayRSSI
          annotations:
            description: >
              Gateway {{ "{{" }} $labels.gatewayId }} has weak signal strength (RSSI ≤-89 dBm over 7d). 
              This indicates poor wireless connectivity that may cause packet loss or connection drops.
              Check antenna positioning, cable connections, or environmental interference.
            summary: >
              Poor gateway signal strength - RSSI ≤-89 dBm (weak signal, connectivity issues likely)
          expr: >
            avg by (gatewayId) (avg_over_time(truvami_gateway_uplink_rssi[7d])) <= -89
          for: 2h
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
            node: "{{ "{{" }} $labels.gatewayId }}"
            service: truvami-gateway
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - alert: TruvamiFairGatewayRSSI
          annotations:
            description: >
              Gateway {{ "{{" }} $labels.gatewayId }} has marginal signal strength (RSSI -89 to -79 dBm over 7d).
              Signal is functional but not optimal. Monitor for further degradation that could impact reliability.
            summary: >
              Fair gateway signal strength - RSSI -89 to -79 dBm (marginal signal, monitor closely)
          expr: >
            avg by (gatewayId) (avg_over_time(truvami_gateway_uplink_rssi[7d])) > -89 and avg by (gatewayId) (avg_over_time(truvami_gateway_uplink_rssi[7d])) <= -79
          for: 1h
          labels:
            namespace: {{ .Release.Namespace }}
            severity: intermediate
            node: "{{ "{{" }} $labels.gatewayId }}"
            service: truvami-gateway
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - alert: TruvamiPoorGatewaySNR
          annotations:
            description: >
              Gateway {{ "{{" }} $labels.gatewayId }} has poor signal quality (SNR ≤8 dB over 7d).
              Signal is barely above noise floor, making demodulation difficult and unreliable.
              Check for interference sources or improve signal path quality.
            summary: >
              Poor gateway signal quality - SNR ≤8 dB (signal barely above noise, demodulation issues)
          expr: >
            avg by (gatewayId) (avg_over_time(truvami_gateway_uplink_snr[7d])) <= 8
          for: 2h
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
            node: "{{ "{{" }} $labels.gatewayId }}"
            service: truvami-gateway
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - alert: TruvamiFairGatewaySNR
          annotations:
            description: >
              Gateway {{ "{{" }} $labels.gatewayId }} has marginal signal quality (SNR 8-10 dB over 7d).
              Signal quality is acceptable but not optimal. Monitor for trends toward degradation
              that could affect LoRa demodulation reliability.
            summary: >
              Fair gateway signal quality - SNR 8-10 dB (marginal signal quality, monitor for degradation)
          expr: >
            avg by (gatewayId) (avg_over_time(truvami_gateway_uplink_snr[7d])) > 8 and avg by (gatewayId) (avg_over_time(truvami_gateway_uplink_snr[7d])) <= 10
          for: 1h
          labels:
            namespace: {{ .Release.Namespace }}
            severity: intermediate
            node: "{{ "{{" }} $labels.gatewayId }}"
            service: truvami-gateway
            {{- with .Values.alertLabels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}