{{- if .Values.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "truvami-monitoring.fullname" . }}-wifi-location
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "truvami-monitoring.labels" . | nindent 4 }}
    {{- with .Values.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.prometheusRule.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  groups:
  - name: truvami.wifi.location
    interval: {{ .Values.prometheusRule.interval | default "30s" }}
    rules:
    # WiFi Solver Error Rate - Multi-level escalation
    - alert: TruvamiWiFiSolverErrorRateMinor
      expr: |
        rate(truvami_wifi_solver_error_count[5m]) / 
        (rate(truvami_wifi_solver_requests_count[5m]) + rate(truvami_wifi_solver_error_count[5m])) > 0.05
      for: 10m
      labels:
        severity: minor
        service: truvami-bridge
        component: wifi-solver
        {{- with .Values.alertLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "Elevated Truvami WiFi solver error rate"
        description: |
          WiFi solver error rate is {{ "{{" }} $value | humanizePercentage }} over the last 5 minutes.
          
          This indicates minor issues with WiFi positioning that may self-resolve.
          
    - alert: TruvamiWiFiSolverErrorRateWarning
      expr: |
        rate(truvami_wifi_solver_error_count[5m]) / 
        (rate(truvami_wifi_solver_requests_count[5m]) + rate(truvami_wifi_solver_error_count[5m])) > 0.15
      for: 5m
      labels:
        severity: warning
        service: truvami-bridge
        component: wifi-solver
        {{- with .Values.alertLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "High Truvami WiFi solver error rate"
        description: |
          WiFi solver error rate is {{ "{{" }} $value | humanizePercentage }} over the last 5 minutes.
          
          This indicates degraded WiFi positioning performance requiring attention.
          
    - alert: TruvamiWiFiSolverErrorRateCritical
      expr: |
        rate(truvami_wifi_solver_error_count[5m]) / 
        (rate(truvami_wifi_solver_requests_count[5m]) + rate(truvami_wifi_solver_error_count[5m])) > 0.30
      for: 2m
      labels:
        severity: critical
        service: truvami-bridge
        component: wifi-solver
        {{- with .Values.alertLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        summary: "Critical Truvami WiFi solver error rate"
        description: |
          WiFi solver error rate is {{ "{{" }} $value | humanizePercentage }} over the last 5 minutes.
          
          This indicates critical issues with WiFi positioning requiring immediate attention:
          - WiFi database connectivity issues
          - Solver service degradation
          - Network connectivity problems
          - High invalid WiFi signature rate

{{- end }}