apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: truvami-integration-alerts
spec:
  groups:
    - name: truvami-bridge-integration-errors
      rules:
        - alert: TruvamiIntegrationErrorsHigh
          annotations:
            description: >-
              High integration error rate at {{ "{{" }} $value }} errors/sec for integration {{ "{{" }} $labels.integration }}.
            summary: >-
              Integration errors detected
          expr: >-
            rate(truvami_integration_error_count[5m]) > 0.05
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: major
            node: truvami-bridge
            namespace: {{ .Release.Namespace }}
            component: integrations

        - alert: TruvamiIntegrationTimeoutErrorsHigh
          annotations:
            description: >-
              High integration timeout error rate at {{ "{{" }} $value }} errors/sec for integration {{ "{{" }} $labels.integration }}.
            summary: >-
              Integration timeout errors detected
          expr: >-
            rate(truvami_integration_timeout_error_count[5m]) > 0.02
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: major
            node: truvami-bridge
            namespace: {{ .Release.Namespace }}
            component: integrations

        - alert: TruvamiIntegrationConnectionErrorsHigh
          annotations:
            description: >-
              High integration connection error rate at {{ "{{" }} $value }} errors/sec for integration {{ "{{" }} $labels.integration }}.
            summary: >-
              Integration connection errors detected
          expr: >-
            rate(truvami_integration_connection_error_count[5m]) > 0.01
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: critical
            node: truvami-bridge
            namespace: {{ .Release.Namespace }}
            component: integrations

    - name: truvami-bridge-wifi-solver-alerts
      rules:
        - alert: TruvamiWiFiSolverErrorsHigh
          annotations:
            description: >-
              High WiFi solver error rate at {{ "{{" }} $value }} errors/sec.
            summary: >-
              WiFi solver errors detected
          expr: >-
            rate(truvami_wifi_solver_error_count[5m]) > 0.1
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: major
            node: truvami-bridge
            namespace: {{ .Release.Namespace }}
            component: wifi-solver

        - alert: TruvamiWiFiSolverTimeoutErrorsHigh
          annotations:
            description: >-
              High WiFi solver timeout error rate at {{ "{{" }} $value }} errors/sec.
            summary: >-
              WiFi solver timeout errors detected
          expr: >-
            rate(truvami_wifi_solver_timeout_error_count[5m]) > 0.02
          for: 2m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: major
            node: truvami-bridge
            namespace: {{ .Release.Namespace }}
            component: wifi-solver

        - alert: TruvamiWiFiSolverResponseTimeSlow
          annotations:
            description: >-
              WiFi solver response time is slow: {{ "{{" }} $value }}ms average over 5 minutes.
            summary: >-
              WiFi solver response time degraded
          expr: >-
            rate(truvami_wifi_solver_response_time_seconds_sum[5m]) / 
            rate(truvami_wifi_solver_response_time_seconds_count[5m]) * 1000 > 5000
          for: 5m
          labels:
            {{- range $key, $value := .Values.alertLabels }}
            {{ $key }}: {{ $value | quote }}
            {{- end }}
            service: truvami-bridge
            severity: minor
            node: truvami-bridge
            namespace: {{ .Release.Namespace }}
            component: wifi-solver