apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
  name: siren-performance
spec:
  groups:
    - name: siren-performance
      rules:
        - alert: SirenMessageProcessingDurationHigh
          annotations:
            description: >-
              Siren message processing duration is {{ "{{" }} $value }}ms over the last 5 minutes.
            summary: >-
              High Siren message processing duration
          expr: >-
            histogram_quantile(0.95, rate(truvami_alerts_message_processing_duration_milliseconds_bucket[5m])) > 5000
          for: 5m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
            node: truvami-siren
            service: truvami-siren
            component: performance
        - alert: SirenWebhookTimeoutHigh
          annotations:
            description: >-
              Siren webhook timeout rate is {{ "{{" }} $value | humanizePercentage }} over the last 5 minutes.
            summary: >-
              High Siren webhook timeout rate
          expr: >-
            rate(truvami_alerts_webhook_timeout_count[5m]) /
            (rate(truvami_alerts_webhook_success_count[5m]) + rate(truvami_alerts_webhook_error_count[5m]) + rate(truvami_alerts_webhook_timeout_count[5m])) > 0.15
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: truvami-siren
            service: truvami-siren
            component: performance
        - alert: SirenRetryQueueBuildup
          annotations:
            description: >-
              Siren retry queue has {{ "{{" }} $value }} items - indicating processing issues.
            summary: >-
              Siren retry queue buildup detected
          expr: >-
            truvami_alerts_retry_queue_depth > 100
          for: 5m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
            node: truvami-siren
            service: truvami-siren
            component: performance
        - alert: SirenDLQMessageRateHigh
          annotations:
            description: >-
              Siren dead letter queue message rate is {{ "{{" }} $value }} messages/sec.
            summary: >-
              High Siren dead letter queue message rate
          expr: >-
            rate(truvami_alerts_dlq_messages_count[5m]) > 0.1
          for: 2m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: major
            node: truvami-siren
            service: truvami-siren
            component: performance
        - alert: SirenMemoryUsageHigh
          annotations:
            description: >-
              Siren memory usage is {{ "{{" }} $value | humanizePercentage }} of available memory.
            summary: >-
              High Siren memory usage
          expr: >-
            process_resident_memory_bytes{job="siren"} / process_virtual_memory_max_bytes{job="siren"} > 0.85
          for: 5m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
            node: truvami-siren
            service: truvami-siren
            component: performance
        - alert: SirenCPUUsageHigh
          annotations:
            description: >-
              Siren CPU usage is {{ "{{" }} $value | humanizePercentage }} over the last 5 minutes.
            summary: >-
              High Siren CPU usage
          expr: >-
            rate(process_cpu_seconds_total{job="siren"}[5m]) > 0.85
          for: 5m
          labels:
            namespace: {{ .Release.Namespace }}
            severity: warning
            node: truvami-siren
            service: truvami-siren
            component: performance
