{{- if and .Values.thanos.enabled (not .Values.thanos.objectStorage.existingSecret.name) }}
{{- if not .Values.thanos.objectStorage.config }}
{{- fail "thanos.enabled=true requires thanos.objectStorage.existingSecret.name OR thanos.objectStorage.config to be set" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "truvami-monitoring.thanos.objstoreSecretName" . }}
  labels: {{- include "truvami-monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  objstore.yml: |
{{ toYaml .Values.thanos.objectStorage.config | indent 4 }}
{{- end }}
