apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "truvami-locksmith.fullname" . }}-migrate
  labels:
    app.kubernetes.io/component: migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        {{- include "truvami-locksmith.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "truvami-locksmith.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/usr/bin/truvami-locksmith"
          args:
            - '--config'
            - /etc/truvami-locksmith/locksmith.yaml
            - 'migrate'
            - '--up'
          env:
            {{- include "truvami-locksmith.databaseEnv" . | nindent 12 }}
          securityContext:
            {{- toYaml .Values.migration.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/truvami-locksmith
              name: config
              readOnly: true
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: "config-locksmith"
            optional: false
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
