apiVersion: v1
kind: Service
metadata:
  name: {{ include "truvami-locksmith.fullname" . }}
  labels:
    {{- include "truvami-locksmith.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.locksmith.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.locksmith.metrics.enabled }}
    - port: {{ .Values.locksmith.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "truvami-locksmith.selectorLabels" . | nindent 4 }}
