apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "truvami-pulse.fullname" . }}-config
  labels:
    {{- include "truvami-pulse.labels" . | nindent 4 }}
data:
  pulse.yaml: |
    {{ .Values.pulse | toYaml | nindent 4 }}
