apiVersion: v1
kind: Service
metadata:
  name: {{ include "truvami-pulse.fullname" . }}
  labels:
    {{- include "truvami-pulse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "truvami-pulse.grpcPort" . }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.pulse.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "truvami-pulse.selectorLabels" . | nindent 4 }}
