apiVersion: v1
kind: Service
metadata:
  name: {{ include "truvami-stream.fullname" . }}
  labels:
    {{- include "truvami-stream.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.stream.server.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.stream.metrics.enabled }}
    - port: {{ .Values.stream.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "truvami-stream.selectorLabels" . | nindent 4 }}
