{{- range $i, $integration := .Values.gateway.integrations }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ $integration.name }}
  labels:
    strimzi.io/cluster: truvami-stack
spec:
  partitions: {{ $integration.topic.partitions | default 3 }}
  replicas: {{ $integration.topic.replicas | default 3 }}
  config: {{ $integration.topic.config | toYaml | nindent 4 }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: "{{ $integration.name }}-error"
  labels:
    strimzi.io/cluster: truvami-stack
spec:
  partitions: {{ $integration.topic.partitions | default 3 }}
  replicas: {{ $integration.topic.replicas | default 3 }}
  config: {{ $integration.topic.config | toYaml | nindent 4 }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ $integration.name }}
  labels:
    strimzi.io/cluster: truvami-stack
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: {{ $integration.name }}
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
      - resource:
          type: topic
          name: "{{ $integration.name }}-error"
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
---
{{ end -}}