apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    strimzi.io/cluster: truvami-stack
spec:
  partitions: {{ .Values.gateway.kafka.topic.partitions | default 3 }}
  replicas: {{ .Values.gateway.kafka.topic.replicas | default 3 }}
  config: {{ .Values.gateway.kafka.topic.config | toYaml | nindent 4 }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: "{{ .Values.gateway.name }}-error"
  labels:
    strimzi.io/cluster: truvami-stack
spec:
  partitions: {{ .Values.gateway.kafka.topic.partitions | default 3 }}
  replicas: {{ .Values.gateway.kafka.topic.replicas | default 3 }}
  config: {{ .Values.gateway.kafka.topic.config | toYaml | nindent 4 }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    strimzi.io/cluster: truvami-stack
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: {{ .Values.gateway.name }}
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
      - resource:
          type: topic
          name: "{{ .Values.gateway.name }}-error"
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
---