{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: truvami-gateway
  labels:
    {{- include "truvami-gateway.labels" . | nindent 4 }}
spec:
  jobLabel: k8s-apps
  selector:
    matchLabels:
    {{- include "truvami-gateway.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: 15s
    path: /
{{- end -}}
