{{- $root := . -}}
{{- range $i, $item := .Values.siren.topics.items }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: "alerts.{{ $item }}"
  labels:
    strimzi.io/cluster: {{ $root.Release.Name }}
spec:
  partitions: {{ $root.Values.kafka.topic.partitions | default 3 }}
  replicas: {{ $root.Values.kafka.topic.replicas | default 3 }}
  config: {{ $root.Values.kafka.topic.config | toYaml | nindent 4 }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: "alerts.{{ $item }}-retry"
  labels:
    strimzi.io/cluster: {{ $root.Release.Name }}
spec:
  partitions: {{ $root.Values.kafka.topic.partitions | default 3 }}
  replicas: {{ $root.Values.kafka.topic.replicas | default 3 }}
  config: {{ $root.Values.kafka.topic.config | toYaml | nindent 4 }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: "alerts.{{ $item }}-dql"
  labels:
    strimzi.io/cluster: {{ $root.Release.Name }}
spec:
  partitions: {{ $root.Values.kafka.topic.partitions | default 3 }}
  replicas: {{ $root.Values.kafka.topic.replicas | default 3 }}
  config: {{ $root.Values.kafka.topic.config | toYaml | nindent 4 }}
---
{{ end -}}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: "truvami-siren-kafka"
  labels:
    strimzi.io/cluster: {{ .Release.Name }}
spec:
  authentication:
    type: tls
  authorization:
    acls:
      # Read/Describe ANY topic starting with "alerts."
      - host: "*"
        operations: ["Read","Describe"]
        resource:
          type: topic
          name: "alerts."
          patternType: prefix

      # Produce/Create to ANY topic starting with "alerts."
      # (Kafka doesn’t support suffix-only ACLs like "*-retry" or "*-dlq")
      - host: "*"
        operations: ["Create","Describe","Write"]
        resource:
          type: topic
          name: "alerts."
          patternType: prefix

      - host: '*'
        operations:
          - Read
          - Write
        resource:
          name: __consumer_offsets
          patternType: literal
          type: topic
      - host: '*'
        operations:
          - Describe
          - Read
          - Write
        resource:
          name: {{ .Release.Name }}
          patternType: literal
          type: group
    type: simple
---