apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "truvami-coverage.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "truvami-coverage.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "truvami-coverage.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "truvami-coverage.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "truvami-coverage.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - '--config'
            - /etc/tile-server/tile-server.yaml
          env:
            - name: TRUVAMI_COVERAGE_TILER_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secretName }}
                  key: {{ .Values.s3.bucketKey }}
            - name: TRUVAMI_COVERAGE_TILER_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secretName }}
                  key: {{ .Values.s3.regionKey }}
            - name: TRUVAMI_COVERAGE_TILER_S3_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secretName }}
                  key: {{ .Values.s3.endpointKey }}
            - name: TRUVAMI_COVERAGE_TILER_S3_FORCEPATHSTYLE
              value: {{ .Values.tiler.s3.forcePathStyle | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secretName }}
                  key: {{ .Values.s3.accessKeyIdKey }}
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.s3.secretName }}
                  key: {{ .Values.s3.secretAccessKeyKey }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.serverImage.repository }}:{{ .Values.serverImage.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.serverImage.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.tilesServer.server.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
