apiVersion: v1
kind: Service
metadata:
  name: {{ include "truvami-coverage.fullname" . }}
  labels:
    {{- include "truvami-coverage.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tilesServer.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "truvami-coverage.selectorLabels" . | nindent 4 }}
