apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "truvami-api.fullname" . }}-migrate
  labels:
    app.kubernetes.io/component: migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ["/usr/bin/truvami-api", "migrate"]
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.database.secretKey }}
                  name: {{ .Values.database.secretName }}
                  optional: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
