apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "truvami-api.fullname" . }}-migrate
  labels:
    app.kubernetes.io/component: migration
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "truvami-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: 
            - "/usr/bin/truvami-api"
          args:
            - '--config'
            - /etc/truvami-api/config.yaml
            - 'migrate'
          env:
            - name: DATABASE_URI
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.database.secretKey }}
                  name: {{ .Values.database.secretName }}
                  optional: false
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}