{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "truvami-api.fullname" . }}
  labels:
    {{- include "truvami-api.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "truvami-api.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: {{ .Values.api.server.port }}
        - protocol: TCP
          port: {{ .Values.api.grpc.port }}
        {{- if .Values.api.metrics.enabled }}
        - protocol: TCP
          port: {{ .Values.api.metrics.port }}
        {{- end }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow HTTPS outbound (for external API calls)
    - to: []
      ports:
        - protocol: TCP
          port: 443
    # Allow HTTP outbound (for health checks and API calls)
    - to: []
      ports:
        - protocol: TCP
          port: 80
    # Allow database connections
    - to: []
      ports:
        - protocol: TCP
          port: 5432
    # Allow Valkey/Redis connections
    - to: []
      ports:
        - protocol: TCP
          port: 6379
{{- end }}
