apiVersion: v1
kind: Service
metadata:
  name: {{ include "truvami-api.fullname" . }}
  labels:
    {{- include "truvami-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.api.server.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.api.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- if .Values.api.metrics.enabled }}
    - port: {{ .Values.api.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "truvami-api.selectorLabels" . | nindent 4 }}
