apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "truvami-docs.fullname" . }}-migrate
  labels:
    {{- include "truvami-docs.labels" . | nindent 4 }}
    app.kubernetes.io/component: migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backoffLimit: 2
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: {{ include "truvami-docs.fullname" . }}-migrate
      labels:
        {{- include "truvami-docs.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migration
    spec:
      restartPolicy: Never
      serviceAccountName: {{ include "truvami-docs.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["migrate"]
          env:
          {{- if .Values.postgres.enabled }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-docs-db-app
                  key: password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-docs-db-app
                  key: username
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@{{ .Release.Name }}-docs-db-pooler:5432/app"
          {{- else if .Values.database.existingSecret }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret }}
                  key: {{ .Values.database.existingSecretKey }}
          {{- else if .Values.database.url }}
            - name: DATABASE_URL
              value: {{ .Values.database.url | quote }}
          {{- else if not .Values.postgres.external.existingSecret }}
            - name: DATABASE_URL
              value: "postgresql://{{ .Values.postgres.external.username }}:{{ .Values.postgres.external.password }}@{{ .Values.postgres.external.host }}:{{ .Values.postgres.external.port }}/{{ .Values.postgres.external.database }}"
          {{- end }}
          {{- if .Values.betterAuth.existingSecret }}
            - name: BETTER_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.betterAuth.existingSecret }}
                  key: {{ .Values.betterAuth.existingSecretKey }}
          {{- end }}
          {{- if .Values.keycloak.existingSecret }}
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keycloak.existingSecret }}
                  key: {{ .Values.keycloak.existingSecretKey }}
          {{- end }}
          {{- if .Values.postgres.external.existingSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.postgres.external.existingSecret }}
          {{- end }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
