{
 "title": "Device",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(truvami_device_uplink_count,devEui)"
    }
   },
   {
    "name": "ports",
    "label": "Ports",
    "query": {
     "query": "label_values(truvami_device_uplink_count,port)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uplinks",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(devEui) (rate(truvami_device_uplink_count{devEui=\"$device\", port=~\"$ports\"}[$interval]))",
     "legendFormat": "Uplinks"
    },
    {
     "expr": "sum by(devEui) (truvami_device_uplink_frame_counter{devEui=\"$device\", port=~\"$ports\"})",
     "legendFormat": "FCount"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(port) (increase(truvami_device_uplink_count{port=~\"$ports\", devEui=\"$device\"}[$interval]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Decoder Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(devEui) (increase(truvami_failed_to_decode_payload_count{devEui=\"$device\", port=~\"$ports\"}[$interval]))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum by(devEui) (increase(truvami_device_uplink_count{devEui=\"$device\", port=~\"$ports\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Decoder Errors by Port",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(port) (increase(truvami_failed_to_decode_payload_count{devEui=\"$device\", port=~\"$ports\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decoder Errors by Port",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(port) (truvami_failed_to_decode_payload_count{devEui=\"$device\", port=~\"$ports\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg by(devEui) (truvami_device_battery_status{devEui=\"$device\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}