{
 "title": "Gateways",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "label_values(truvami_device_uplink_count,devEui)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "gateways",
    "label": "Gateways",
    "query": {
     "query": "label_values(truvami_gateway_uplink_rssi,gatewayId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RSSI by devices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "avg by(devEui) (truvami_gateway_uplink_rssi{devEui=~\"$devices\", gatewayId=~\"$gateways\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RSSI by gateways",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "avg by(gatewayId) (truvami_gateway_uplink_rssi{devEui=~\"$devices\", gatewayId=~\"$gateways\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNR by devices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(devEui) (truvami_gateway_uplink_snr{devEui=~\"$devices\", gatewayId=~\"$gateways\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SNR by devices",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg by(gatewayId) (truvami_gateway_uplink_snr{devEui=~\"$devices\", gatewayId=~\"$gateways\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}