{
 "title": "Positions",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "customers",
    "label": "Customers",
    "query": {
     "query": "label_values(truvami_device_uplink_count,customer)"
    }
   },
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "label_values(truvami_device_uplink_count,devEui)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Positions ttf by devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(devEui) (truvami_device_gnss_time_to_first_fix_value{customer=~\"$customers\", devEui=~\"$devices\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Positions pdop by devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg by(devEui) (truvami_device_gnss_pdop_value{customer=~\"$customers\", devEui=~\"$devices\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Positions satellites by devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg by(devEui) (truvami_device_gnss_satellites_value{customer=~\"$customers\", devEui=~\"$devices\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}