{
 "title": "Reset",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "label_values(truvami_device_reset_count,devEui)"
    }
   },
   {
    "name": "reasons",
    "label": "Reasons",
    "query": {
     "query": "label_values(truvami_device_reset_count,reason)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resets",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(devEui) (increase(truvami_device_reset_count{devEui=~\"$devices\", reason=~\"$reasons\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reasons",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(reason) (increase(truvami_device_reset_count{devEui=~\"$devices\", reason=~\"$reasons\"}[1h]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  { "title": "Reasons", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "$reasons",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "repeat": "reasons",
   "targets": [
    {
     "expr": "sum by(devEui) (increase(truvami_device_reset_count{devEui=~\"$devices\", reason=\"$reasons\"}[1h]))",
     "legendFormat": "{{devEui}}"
    }
   ]
  }
 ]
}