{
 "title": "Service - truvami-api",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(up,namespace)" } },
   { "name": "service", "query": "truvami-api" }
  ]
 },
 "panels": [
  {
   "title": "Service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (ALERTS{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truvami_api_info{namespace=\"$namespace\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Build Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "truvami_api_info{namespace=\"$namespace\"}",
     "legendFormat": "{{build_date}}"
    }
   ]
  },
  { "title": "Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (ALERTS{namespace=\"$namespace\", service=\"$service\", severity=\"critical\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (ALERTS{namespace=\"$namespace\", service=\"$service\", severity=\"major\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (ALERTS{namespace=\"$namespace\", service=\"$service\", severity=\"minor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (ALERTS{namespace=\"$namespace\", service=\"$service\", severity=\"warning\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Intermediate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (ALERTS{namespace=\"$namespace\", service=\"$service\", severity=\"intermediate\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(severity) (ALERTS{namespace=\"$namespace\", service=\"$service\", severity=\"info\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "List", "type": "alertlist", "gridPos": { "h": 15, "w": 18, "x": 0, "y": 7 } },
  {
   "title": "Alerts",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(alertname) (ALERTS{namespace=\"$namespace\", service=\"$service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Go", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_info{namespace=\"$namespace\", container=\"$service\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg_over_time(go_memstats_heap_alloc_bytes{namespace=\"$namespace\", container=\"$service\"}[$__interval])",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "avg_over_time(go_threads{namespace=\"$namespace\", container=\"$service\"}[$__interval])",
     "legendFormat": "Threads"
    }
   ]
  }
 ]
}