{
 "title": "Troubleshooting",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PG_DATASOURCE", "query": "grafana-postgresql-datasource" },
   {
    "name": "devices",
    "label": "Devices",
    "query": "SELECT device from positions WHERE pdop >= 0;"
   }
  ]
 },
 "panels": [
  {
   "title": "Solver",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Wi-Fi solver error rate",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 99 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 * sum(rate(google_wifi_solver_error_total[$__rate_interval])) / (sum(rate(google_wifi_solver_error_total[$__rate_interval])) + sum(rate(google_wifi_solver_success_total[$__rate_interval])))\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Source",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$devices",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 37 },
     "repeat": "devices",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT source, COUNT(*) FROM positions WHERE (device IN ($devices)) AND source = 'wifi' GROUP BY source, device"
      },
      {
       "rawSql": "SELECT source, COUNT(*) FROM positions WHERE (device IN ($devices)) AND source = 'gnss' GROUP BY source, device"
      }
     ]
    }
   ]
  },
  {
   "title": "PDOP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$devices",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 38 },
     "repeat": "devices",
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FROM positions WHERE pdop >= 20  AND device IN ( $devices );"
      },
      {
       "rawSql": "SELECT COUNT(*) FROM positions WHERE pdop >= 0 AND pdop < 10 AND device IN ( $devices ) "
      },
      {
       "rawSql": "SELECT COUNT(*) FROM positions WHERE pdop >= 10 AND pdop < 20 AND device IN ( $devices ) "
      }
     ]
    }
   ]
  },
  { "title": "$devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 }, "repeat": "devices" },
  {
   "title": "PDOP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT captured_at AS \"time\", pdop AS \"value\" FROM positions WHERE (device IN ($devices) AND pdop IS NOT NULL) LIMIT 5000 "
    }
   ]
  },
  {
   "title": "TTF",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT captured_at AS \"time\", ttf AS \"value\" FROM positions WHERE (device IN ($devices) AND ttf IS NOT NULL) LIMIT 5000"
    }
   ]
  },
  {
   "title": "PDOP (avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(pdop) FROM positions WHERE device IN ($devices) LIMIT 5000 \n"
    }
   ]
  },
  {
   "title": "TTF (avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(ttf) FROM positions WHERE device IN ($devices) LIMIT 5000 \n"
    }
   ]
  }
 ]
}