{
 "title": "truvami-device",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(up,namespace)" } },
   { "name": "service", "query": "truvami-device" },
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "label_values(truvami_device_uplink_count{namespace=\"$namespace\"},devEui)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alarms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (ALERTS{namespace=\"$namespace\", devEui=~\"$devices\", severity=\"critical\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Major",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (ALERTS{namespace=\"$namespace\", devEui=~\"$devices\", severity=\"major\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Minor",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (ALERTS{namespace=\"$namespace\", devEui=~\"$devices\", severity=\"minor\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (ALERTS{namespace=\"$namespace\", devEui=~\"$devices\", severity=\"warning\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Intermediate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (ALERTS{namespace=\"$namespace\", devEui=~\"$devices\", severity=\"intermediate\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(severity) (ALERTS{namespace=\"$namespace\", service=~\"$devices\", severity=\"info\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "List", "type": "alertlist", "gridPos": { "h": 15, "w": 18, "x": 0, "y": 4 } },
  {
   "title": "Alerts",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(alertname) (ALERTS{namespace=\"$namespace\", devEui=~\"$devices\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Uplinks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Uplinks per hour",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "uplinks/h" } },
   "targets": [
    {
     "expr": "avg by(devEui) (rate(truvami_device_uplink_count{devEui=~\"$devices\"}[1h])) * 60 * 60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}