{
 "title": "Uplinks",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "label_values(truvami_device_uplink_count,devEui)"
    }
   },
   {
    "name": "ports",
    "label": "Ports",
    "query": {
     "query": "label_values(truvami_device_uplink_count,port)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Uplinks",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(devEui) (increase(truvami_device_uplink_count{devEui=~\"$devices\", port=~\"$ports\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(port) (increase(truvami_device_uplink_count{devEui=~\"$devices\", port=~\"$ports\"}[1h]))",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Decoder Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(port) (increase(truvami_failed_to_decode_payload_count{devEui=~\"$devices\", port=~\"$ports\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}