{
 "title": "Wi-Fi Solver",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "devices",
    "label": "Devices",
    "query": {
     "query": "label_values(truvami_device_uplink_count,devEui)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uplinks",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(__name__) (increase(truvami_device_uplink_count[$interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by(__name__) (increase(truvami_wifi_solver_requests_count[$interval]))",
     "legendFormat": "Wi-Fi"
    },
    {
     "expr": "sum by(__name__) (increase(truvami_wifi_zero_position_count[$interval]))",
     "legendFormat": "Wi-Fi"
    }
   ]
  },
  {
   "title": "Wi-Fi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 / sum by(__name__) (increase(truvami_device_uplink_count[$interval])) * sum by(__name__) (increase(truvami_wifi_solver_requests_count[$interval]))",
     "legendFormat": "Wi-Fi"
    }
   ]
  },
  {
   "title": "Wi-Fi",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(__name__) (increase(truvami_wifi_solver_requests_count[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Zero Positions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 / sum by(__name__) (increase(truvami_wifi_solver_requests_count[$interval])) * sum by(__name__) (increase(truvami_wifi_zero_position_count[$interval]))",
     "legendFormat": "Wi-Fi"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 / sum by(__name__) (increase(truvami_wifi_solver_requests_count[$interval])) * sum by(__name__) (increase(truvami_wifi_solver_error_count[$interval]))",
     "legendFormat": "Wi-Fi"
    }
   ]
  },
  {
   "title": "Zero Positions #Access Points",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(accessPointCount) (increase(truvami_wifi_zero_position_count[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}