layers:
  a:
    file: a.csv
    source: POSITION_SOURCE_GNSS_ACTIVE
    connections:
      - to: b
        dwell:
          min: 30s
          max: 2m

  b:
    file: b.csv
    source: POSITION_SOURCE_GNSS_ACTIVE
    connections:
      - to: c
        dwell:
          min: 30s
          max: 2m
      - to: i
        dwell:
          min: 30s
          max: 2m

  c:
    file: c.csv
    source: POSITION_SOURCE_GNSS_ACTIVE
    connections:
      - to: d
        dwell:
          min: 1m
          max: 3m

  d:
    file: d.csv
    source: POSITION_SOURCE_BLE
    connections:
      - to: e
        dwell:
          min: 1m
          max: 3m
      - to: h
        dwell:
          min: 1m
          max: 3m

  e:
    file: e.csv
    source: POSITION_SOURCE_GNSS_ACTIVE
    connections:
      - to: f
        dwell:
          min: 30s
          max: 2m

  f:
    file: f.csv
    source: POSITION_SOURCE_BLE
    connections:
      - to: g
        dwell:
          min: 1m
          max: 3m

  g:
    file: g.csv
    source: POSITION_SOURCE_GNSS_ACTIVE
    connections:
      - to: j
        dwell:
          min: 30s
          max: 2m

  h:
    file: h.csv
    source: POSITION_SOURCE_GNSS_ACTIVE
    connections:
      - to: a
        dwell:
          min: 30s
          max: 2m

  i:
    file: i.csv
    source: POSITION_SOURCE_GNSS_ACTIVE
    connections:
      - to: j
        dwell:
          min: 30s
          max: 2m

  j:
    file: j.csv
    source: POSITION_SOURCE_GNSS_ACTIVE
    connections:
      - to: a
        dwell:
          min: 30s
          max: 2m
