apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "truvami-seedbox.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    {{- include "truvami-seedbox.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "truvami-seedbox.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "truvami-seedbox.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "truvami-seedbox.serviceAccountName" . }}
      {{- $defaultPodSecCtx := dict "runAsNonRoot" true "fsGroup" 1000 }}
      {{- $podSecCtx := mustMergeOverwrite $defaultPodSecCtx (.Values.podSecurityContext | default dict) }}
      securityContext:
        {{- toYaml $podSecCtx | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
            - '--config'
            - /etc/truvami-seedbox/seedbox.yaml
          command:
            - /usr/bin/truvami-seedbox
          {{- $defaultSecCtx := dict "allowPrivilegeEscalation" false "readOnlyRootFilesystem" true "runAsNonRoot" true "runAsUser" 1000 "runAsGroup" 1000 "capabilities" (dict "drop" (list "ALL")) "seccompProfile" (dict "type" "RuntimeDefault") }}
          {{- $secCtx := mustMergeOverwrite $defaultSecCtx (.Values.securityContext | default dict) }}
          securityContext:
            {{- toYaml $secCtx | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.seedbox.metrics.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /etc/truvami-seedbox
              name: config
              readOnly: true
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ include "truvami-seedbox.fullname" . }}-config
            optional: false
          name: config
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
