apiVersion: v1
kind: Service
metadata:
  name: {{ include "truvami-seedbox.fullname" . }}
  labels:
    {{- include "truvami-seedbox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.seedbox.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "truvami-seedbox.selectorLabels" . | nindent 4 }}
