{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "truvami-seedbox.fullname" . }}
  labels:
    {{- include "truvami-seedbox.labels" . | nindent 4 }}
spec:
  jobLabel: k8s-apps
  selector:
    matchLabels:
    {{- include "truvami-seedbox.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: 15s
{{- end -}}
